spring:
  application:
    name: student-management-system

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}


info:
  app:
    name: Student Management Service
    description: Student CRUD Application
    version: 1.0.0
    environment: ${SPRING_PROFILES_ACTIVE}

management:
  info:
    env:
      enabled: true
